### PR TITLE
MANIFEST.in: Add docs and test data

### PR DESCRIPTION
**Pull request by jayvdb**
Closes https://github.com/tableau/server-client-python/issues/779

### CODE REVIEW

**Review by t8y8 — APPROVED** [review]

**Comment by shinchris** [comment]
@jayvdb thanks for submitting this pull request - change looks good!

Before we merge this in, could you change the base branch to 'development' rather than master?
Also, could you read and send a [CLA](https://tableau.github.io/contributing.html) to github@tableau.com if you haven't already? 

Thanks!

**Comment by jayvdb** [comment]
Switched branch the easy way here on Github.  I'll do the CLA and rebase this PR properly.  Worth noting that no CLA request occurred on https://github.com/tableau/TabPy/pull/473 .  There are automated CLA bots which IMO would be a good idea if the intention is to catch all contributors.

**Comment by jayvdb** [comment]
Ugh. https://tableau.github.io/2017.02-TableauIndividualCLA.pdf is not an e-form PDF.  How are we supposed to electronically sign it as mentioned on https://tableau.github.io/contributing.html ?  Use a PDF editor, potentially injecting some modification into the text that your lawyers need to manually check for ?

**Comment by bcantoni** [comment]
@jayvdb yes we are looking at improving the process with CLAbot in the future but at the moment are still using the PDF + email path.

**Comment by bcantoni** [comment]
Hi @jayvdb sorry for the inconvenience on our current PDF based solution. (A better way is in the works.) I did just test with Adobe Acrobat Reader (free version) and using the "Sign & Fill" option it does work on this particular PDF.

**Comment by jayvdb** [comment]
Sent via DocuSign.  Hopefully that does the trick.

**Comment by bcantoni** [comment]
@jayvdb received the CLA and everything looks good, thanks! @shinchris this is ready now from a CLA perspective.

**Comment by shinchris** [comment]
Thanks @jayvdb!

**Pull request merged**
