### PR TITLE
feat: add JWTAuth

### PR DESCRIPTION
**Pull request by jorwoods**
Add `JWTAuth` class, as well as allowing Token auth to do impersonation.

### CODE REVIEW

**Review by jacalata — CHANGES_REQUESTED** [review]
Could you just add a __repr__ function for the JWTAuth class? something like 
        return "<jwt token={} site={}>".format(self.jwt[:5]+ "...", self.site_id)

**Comment by jorwoods** [comment]
Done. How do you feel about explicitly marking the `Credentials.__repr__` and `Credentials.credentials` as abstractmethods?

Additionally, I feel like `sign_in_with_personal_access_token` should be deprecated since it is just a redundant passthrough.

**Comment by jorwoods** [comment]
Was there something missing from this PR that I should have implemented?

**Comment by jacalata** [comment]
oops, I think this got auto-closed when I merged the dev branch

**Comment by ngohuuduc** [comment]
Hello, 
Is there any update regarding to this matter ?

**Pull request merged**
