### PR TITLE
feat: accept parameters for post endpoint

### PR DESCRIPTION
**Pull request by Udit107710**
This will allow request parameters like timeout
to be set by user. Because the metadata api use
post_request endpoint, that endpoint will also
support adding request parameters.
This feature was already present in the GET
endpoint

Related issue: #849

### CODE REVIEW

**Comment by bcantoni** [comment]
Hi @Udit107710 thanks for the pull request!

While we wait for a review we'll also need to ask you to submit a Contributor License Agreement - details are listed here: http://tableau.github.io/contributing.html

**Comment by t8y8** [comment]
Generally speaking, this is probably a good idea!

However, curious the use case -- the GraphQL API itself has a server-side timeout of 60 seconds by default, is there a reason you want to set that on the client side to a lower value?

**Comment by Udit107710** [comment]
@t8y8 I did not know about the 60 sec timeout. But even then, I think it will be good to have common functionality across the endpoints

**Comment by bcantoni** [comment]
Thanks Udit for the CLA; updated tags here to reflect.

**Comment by t8y8** [comment]
@Udit107710 fair enough -- but yeah the metadata api times out 60 seconds by default, and returns an error on the `error` payload.

Still, change is reasonable -- can you target it against `development` instead of `master`? I'm also not sure if the formatting will match the formatter or not; you can run `black` against the file to see.

**Comment by Udit107710** [comment]
@jacalata I think you have incorrectly merged development into my branch

**Comment by Udit107710** [comment]
@t8y8 Ran the check by pycodestyle and that passed. Didn't know about the check by black. Checking and updating branch

**Comment by t8y8** [comment]
This PR doesn't have the "auto mergeable" checkmark which makes me somewhat nervous -- I think because it was branched from master, it includes the issue template (which we don't need in dev). Can you rebase on development rather than retarget the PR? That should fix it... I think.

Otherwise looks good.

**Comment by bcantoni** [comment]
Thanks @t8y8 good catch - @Udit107710 I think if you rebase this PR against the current `development` branch here, that should fix it.

**Comment by bcantoni** [comment]
@Udit107710 reminder ping on this one - could you please rebase your branch from the current `tableau:development` branch? Then we should be able to merge.

**Comment by jacalata** [comment]
I fixed the conflict, it was an update in content type.

**Comment by Udit107710** [comment]
> 
> 
> I fixed the conflict, it was an update in content type.

Thanks @jacalata

**Pull request merged**
