### PR TITLE
Add workbook and datasource name attributes to JobItem Model

### PR DESCRIPTION
**Pull request by ivanB1975**
Added the workbook_name to the attributes of the jobItem Model. Added also the test.

### CODE REVIEW

**Comment by ivanB1975** [comment]
Cla is signed

**Comment by jorwoods** [comment]
@ivanB1975 I think if you're going to pull out workbook name, then you should pull out the datasource name as well.

**Comment by ivanB1975** [comment]
> @ivanB1975 I think if you're going to pull out workbook name, then you should pull out the datasource name as well.

Thanks for having a look at it. Ok, I will need to check this

**Comment by ivanB1975** [comment]
@jorwoods I added the datasource name as well

**Comment by bcantoni** [comment]
I'll try close and reopen the PR to refresh the CLA bot status.

**Review by jacalata — APPROVED** [review]

**Pull request merged**
