### PR TITLE
Add support to datasource and workbook revisions

### PR DESCRIPTION
**Pull request by elsherif**
Add support to datasource and workbook revisions (get all item revisions / download item by revision number)

### CODE REVIEW

**Comment by t8y8** [comment]
@elsherif sorry for the poor timing, but we just merged a big change to some of the same underlying files that add type hints to the function signatures -- would you be able to rebase on those changes, as well as consider adding type hints as well?

**Comment by elsherif** [comment]
@t8y8 I rebased but I got some errors after adding the type hints, so I removed them now.

**Comment by t8y8** [comment]
The problem is that the embedded fetcher makes it so `_thing` returns something like `Callable[[], List["WorkbookItem"]]) -> None` and then the property `thing` just returns the `List[WorkbookItem]`

**Comment by elsherif** [comment]
@t8y8 can someone from Dev team add a commit for that so you can merge?

**Comment by t8y8** [comment]
@jorwoods since you're on a type hinting spree -- if we merge this without would you want to go through and add them in? If that's the case I can give this a review this week.

**Comment by jorwoods** [comment]
Yeah, I can add the type hints later.

**Review by jacalata — APPROVED** [review]
looks good to me

**Comment by jacalata** [comment]
merging, type hints can come later

**Comment by t8y8** [comment]
Just a note we also merged this without tests which isn't ideal

**Pull request merged**
