### PR TITLE
docs: docstrings for user item and endpoint

### PR DESCRIPTION
**Pull request by jorwoods**

### CODE REVIEW

**Review by jacalata — APPROVED** [review]
This is great. Are you doing it manually? We do have most of this in the REST docs.

**Comment by jorwoods** [comment]
Its a mix of copying information in from https://tableau.github.io/server-client-python/docs/api-ref, https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref.htm, and adding some extra detail where appropriate. The main thing I'm unsure of is detailing all of the ServerResponseError codes and details or if it should just point them to the server REST API docs for that detail.

**Comment by jorwoods** [comment]
The reason for pulling this info into docstrings from the docs is if we go forward with the rewrite per #1451, then we could pull the docstrings in as the documentation. Making it available both in the web and in the IDE.

**Comment by jacalata** [comment]
I think it's probably easier to point to the existing docs for error codes. Some of them have a pretty long list of possible return codes

**Pull request merged**
