### PR TITLE
parse_datetime() should gracefully handle invalid dates

### PR DESCRIPTION
**Pull request by paulvic**
We've seen instances where enumerating workbooks on our server results in an exception in parse_datetime(). It appears that some workbooks contain invalid dates e.g. `2018-06-31T13:12:00Z` for their created_at or updated_at times which causes the method to throw an exception, breaking enumeration.

This change simply catches the parsing failure and returns `None` in that scenario.

### CODE REVIEW

**Comment by t8y8** [comment]
Hey @paulvic! I’ve retargeted this against `development`.

Can you confirm you’ve signed the CLA and sent it in?

Once I hear back I’ll take a look.

Side note, do you have any idea why there are invalid time stamps in the mix?

**Comment by paulvic** [comment]
> Hey @paulvic! I’ve retargeted this against `development`, but could you rebase the PR? It looks like it picked up some changes around docs from master.
> 
> Can you confirm you’ve signed the CLA and sent it in?
> 
> Once I hear back I’ll take a look.
> 
> Side note, do you have any idea why there are invalid time stamps in the mix?

I'll send a.signed CLA.today.

No, I have no idea how the invalid timestamps got there.

**Comment by james-baker** [comment]
CLA received and approved.

**Comment by bcantoni** [comment]
Hi @paulvic we are getting caught up on some old contributions and realize this one was never merged. Would you be able to rebase your branch off the current `development` branch and do a force push? Then we should be able to wrap this one up.

**Comment by paulvic** [comment]
> Hi @paulvic we are getting caught up on some old contributions and realize this one was never merged. Would you be able to rebase your branch off the current `development` branch and do a force push? Then we should be able to wrap this one up.

hi @bcantoni, that's all done now & tests passed 👍

**Pull request merged**
