### PR TITLE
Fix QuerySet slicing logic

### PR DESCRIPTION
**Pull request by jorwoods**
The old logic for handling slices on QuerySet objects worked for toy examples when the result set was small, but would crash if having to work through too many items. This logic will work for  all sizes of results.

### CODE REVIEW

**Comment by jacalata** [comment]
looks good, I know I've made it a little ugly with the rebasing. 

Is it possible to write a test that shows this fix? What kind of sizes were you seeing the crash at?

**Comment by jacalata** [comment]
(I will fix the conflicts/merge it, don't worry about those)

**Comment by jorwoods** [comment]
Turns out the real issue was it trying to span pages. I have a better fix incoming. Working on writing the test for it.

**Comment by jorwoods** [comment]
The real issue was requesting an index that was a multiple of the page size, which would happen when trying to span pages when slicing. It would get stuck in an infinite loop whenever the requested item number is a multiple of the page size. Fixed this by incrementing the `k` number by 1 whenever the requested index is not in the current cache's range. This makes it so that the function will increment to the next page as appropriate when the slice requires it.

**Pull request merged**
