### PR TITLE
Issue 1299

### LINKED ISSUE #1299: Server Response Errror (Bad Request) when overwriting large hyperfile since v0.26
**Describe the bug**
When updating from version 0.25 to 0.26, we found that one of our scripts which overwrites a datasource started failing.
We have narrowed down the source of the bug to the following change:
https://github.com/tableau/server-client-python/commit/307d8a20a30f32c1ce615cca7c6a78b9b9bff081#r130310838

This error occurs with our servers running version 2022.1.13, 

**Versions**
Details of your environment, including:
 - Tableau Server version: bug present when using 2022.1.13, but not with 2022.1.16
 - Python version 3.9
 - TSC library version 0.26+

**To Reproduce**
Upload a large hyperfile, ours causing the error is 150+ MB.

**Results**
```
    raise ServerResponseError.from_response(server_response.content, self.parent_srv.namespace, url)
tableauserverclient.server.endpoint.exceptions.ServerResponseError:

        400011: Bad Request
                There was a problem publishing the file
```

### PR DESCRIPTION
**Pull request by kykrueger**
closes #1299 

Fixes issue with bad state of async_response.
Fixes issue that timeouts are not triggered when set to longer than 60s.

### CODE REVIEW

**Comment by kykrueger** [comment]
I've signed the CLA

**Comment by bcantoni** [comment]
Close and reopen PR to run CLA check again.

**Comment by bcantoni** [comment]
@kykrueger thanks for putting this PR together! As a first time contributor we had to click a button to run all the checks here and those are done now. You are all set from the CLA perspective. If you look at the build results it looks like you have one black formatting issue and one by pi type issue to fix.

In parallel, @jacalata could you give this a review?

**Comment by kykrueger** [comment]
Alright, I'll run black over it once. Are you using the defaults or the --preview flag?

**Comment by jacalata** [comment]
Defaults

**Comment by kykrueger** [comment]
@jacalata @bcantoni that should do it

**Comment by kykrueger** [comment]
@jacalata @bcantoni the mypy failures are not functionally related to the PR. Do you have a suggestion?

**Comment by kykrueger** [comment]
To push this along I've added a check to see if exceptions are returned from the blocking request. This was already returned before this PR, but the type hinting didn't reveal the possibility.

When making my changes, I fixed a pyright error where it had complained that Exceptions could be returned, but were not hinted. This broke the checks for mypy.

Now the returned exceptions will be raised. Before a typeerror would have probably occurred, but now the proper exception will be raised.

**Review by jacalata — APPROVED** [review]
This looks great, thanks! I'd like to add some tests with it, but if I don't get round to that I'll merge it this week anyway.

**Comment by kykrueger** [comment]
Thanks!

**Comment by kykrueger** [comment]
@jacalata , I adjusted the settings of my config for Black to match those of your tests.
Now that we both have 120 as the line length, I expect all builds to pass.

**Comment by kykrueger** [comment]
@bcantoni @jacalata could you give an Update on what is holding up this ticket?

**Comment by mzappitello** [comment]
is there any update on this PR? our workflows ran into the same error described by @kykrueger and we had to revert back to `v0.25`.

**Review by jacalata — APPROVED** [review]

**Review by jacalata — APPROVED** [review]

**Pull request merged**
