### PR TITLE
190 update datasource connection

### PR DESCRIPTION
**Pull request by MouradHRM**
Feature Add : Update Datasource Connection
On a similar way Update Workbook Connection works

### CODE REVIEW

**Comment by RussTheAerialist** [comment]
Hi! Thank you so much for your contribution!

Before we can take a look at it, and start the feedback process, we'll need to have you sign our Contributors Licensing Agreement.  You can find information on how to submit that here: https://tableau.github.io/contributing.html .

Once we have it, we can take a look and get your change merged in.

**Comment by t8y8** [comment]
@MouradHRM this has some conflicts with HEAD (would you like to rebase and update?).

Additionally, have you had a chance to fill out the CLA?

**Comment by t8y8** [comment]
@MouradHRM following up on this -- have you had a chance to submit the CLA and would you still like to push this update through?

**Comment by RussTheAerialist** [comment]
I verified that a CLA is on file, but we have some conflicts that need to be cleaned up before we can accept this.  It's been a few months since the last update, so I'm going to close it for now.

Feel free to reopen once you have resolved the conflict.

**Pull request closed without merging**
