### PR TITLE
Adds description as a read-only attribute of WorkbookItem

### PR DESCRIPTION
**Pull request by JorgeFonseca**
This exposes the description field that is returned by the API as a read-only attribute on the WorkbookItem model.

### CODE REVIEW

**Comment by JorgeFonseca** [comment]
@shinchris I can't request review for this. I might've misread the contributing guidelines though, what should I do to unblock?

**Comment by shinchris** [comment]
Thanks for making the change! 😃 🚀 
I'm not sure why you aren't able to request reviewers, but it looks good to merge in.

In order to proceed with the merge, could you read and sign our CLA?
http://tableau.github.io/contributing.html

**Comment by JorgeFonseca** [comment]
Thank you @shinchris.
Just mailed the CLA.

**Comment by james-baker** [comment]
CLA received and approved.

**Pull request merged**
