### PR TITLE
226 fix populate connections bug

### PR DESCRIPTION
**Pull request by grbritz**
This address issue #226

### CODE REVIEW

**Comment by t8y8** [comment]
Ok, I just confirmed we have no test coverage on `populate_connections` at all, that's why it didn't get caught.

**Comment by RussTheAerialist** [comment]
Can we have a test added as part of this fix?  I’ll do an emergency release
as 0.5.1 tomorrow.

**Comment by t8y8** [comment]
@grbritz might not know how to mock it all out. I will see if I can get him the code tonight and he can copy/paste

**Comment by RussTheAerialist** [comment]
:ship: okay then I'm going to merge this PR and get a new release out this morning to make sure we don't break too many people.  @t8y8 are the tests something you could work on?  I have some other bugs on my plate right now that need to take priority for various reasons.

**Comment by grbritz** [comment]
@RussTheAerialist Thanks for merging. I'll see if I can figure out how to add the mocks but I have other more urgent tasks I need to get to today. FYI if you didn't know, my PR was into the development branch, so users of the master branch will still be experiencing the issue.

**Comment by RussTheAerialist** [comment]
Thanks @grbritz !  Let me or @t8y8 know if you need any help (feel free to drop by), I'm working on getting it into master #228 and then will release a new one on pypi.

**Comment by t8y8** [comment]
@RussTheAerialist yeah I'll work on it -- I need those tests for 'pager all the things' anyway!

**Pull request merged**
