### PR TITLE
Site can now be queried by name

### PR DESCRIPTION
**Pull request by VathsalaAchar**
This is a Nice To Have for our end. We prefer to work with names rather than ids.

### CODE REVIEW

**Comment by t8y8** [comment]
@VathsalaAchar thank you for the PR!

I've tagged it as an 'enhancement' and we will take a look.

I need to confirm that we want to do this via the legacy endpoint (the key=name) method, and not be leveraging native filtering, or something like that.

In the mean time, please fill out the CLA, as documented here: http://tableau.github.io/contributing.html

Thanks!

/cc @LGraber @RussTheAerialist

**Comment by VathsalaAchar** [comment]
@t8y8 thank you for the input. We sent in the CLA yesterday and I got a confirmation that it was filed for your records. I have also rebased the PR as asked.

**Comment by t8y8** [comment]
@VathsalaAchar it looked like you added in some work from the 'inprogress' branch.

That branch is way outta date, and the permissions changes aren't relevant to your original PR -- was that intentional?

It looks like your changes are made against a `master` base though the PR is submitted against `development`. This has the side effect of missing a largeish change where all endpoints take an annotation that specifies the versions it's compatible with.

Can you stash just your changes on and push them to a new branch made from `development`? That should clear up any possible merge conflicts :)

**Comment by t8y8** [comment]
This is related to #49

**Comment by VathsalaAchar** [comment]
@t8y8 No that wasn't intentional, I'll fix the in progress and the master branch mess. Apologies for that!

**Comment by VathsalaAchar** [comment]
I have made a PR in #153 so I'll close this now. Thank you for all your help @t8y8 .

**Pull request closed without merging**
