### PR TITLE
Small improvements (better test cases; less dead code)

### PR DESCRIPTION
**Pull request by vogelsgesang**
This pull request contains a couple of small improvements (better test cases; deleted some dead code)

### CODE REVIEW

**Review by t8y8 — APPROVED** [review]
🚀

**Comment by vogelsgesang** [comment]
@t8y8 I don't have merge permissions for this repo. Can you please merge this if it passes whichever quality gates you deem appropriate?

**Comment by bcantoni** [comment]
@vogelsgesang you should have push permissions now, so give it a try.

**Comment by vogelsgesang** [comment]
worked!
Rebased the my PR on the `development` branch and merged it

**Pull request merged**
