### PR TITLE
Hotfix schedule_item.py for issue 1237

### PR DESCRIPTION
**Pull request by austinpeters-gohealthuccom**
Hotfix for https://github.com/tableau/server-client-python/issues/1237

### CODE REVIEW

**Comment by austinpeters-gohealthuccom** [comment]
image

**Comment by jacalata** [comment]
@austinpeters-gohealthuccom are you able to reformat this for our style checker?

**Comment by austinpeters-gohealthuccom** [comment]
I literally commented out 3 lines and that's it. Means whoever committed the last branch got a bypass.

**Comment by gary-beautypie** [comment]
Think it just wants spaces between the # and the commented code?

**Comment by LennartKloppenburg** [comment]
Hello, I stumbled on this exact issue and I was wondering if there is any scheduled release/merge of this fix?

**Pull request merged**
