### PR TITLE
Enable switch site functionality

### PR DESCRIPTION
**Pull request by jorwoods**
Adds capability for a user to switch sites using the REST API.

### CODE REVIEW

**Comment by jorwoods** [comment]
@RussTheAerialist I have already signed and sent in the CLA.

**Comment by RussTheAerialist** [comment]
@jorwoods I wasn't able to find you in our list of signed people, though I see you've contributed in the past, So it's probably a record-keeping error on our part. I'm double-checking with our legal team who keeps the hard copies to make sure we have it. Thanks for understanding!

**Comment by RussTheAerialist** [comment]
@jorwoods Our legal team couldn't find any record of it either, I'm afraid.  Do you mind resending it to github@tableau.com ? I  am sorry that we seem to have lost track of the original CLA, and I hope this isn't too much of an inconvenience.

**Comment by jorwoods** [comment]
@RussTheAerialist Not a problem. Resent it. Let me know if that doesn't satisfy the need.

**Comment by RussTheAerialist** [comment]
Got it now! Thank you for responding so quickly!

**Comment by jorwoods** [comment]
I know this already got approved, but since it hasn't been merged yet, one looming question: It technically produces an error if the user tries to switch sites to their current site. Should the user handle that within their code, or should that be handled quietly within TSC?

**Comment by t8y8** [comment]
@jorwoods Do we really throw an error on that, happen to know which HTTP code we throw? (I might have even been the PM for the API at that time, so it's maybe my fault).

My first thought is just to swallow it and ignore, I could see certain user code switching to self just to be safe in certain scenarios and not wanting an error... what do you think?

If we do want to go that route, there are a few examples of how we do that today. The preference is to create a a new specific exception, then catch it and swallow, and rethrow anything else.

**Pull request merged**
