### PR TITLE
BugFix Issue#79 Add Guest to site role enum

### PR DESCRIPTION
**Pull request by Kovner**
Fixes issue where Guest user was not a valid user_item

### CODE REVIEW

**Comment by Kovner** [comment]
bitmoji

**Comment by t8y8** [comment]
We don't currently have validating tests for the 'positive' case on the model (we only test invalid cases :'( ) so I'm ok with this one-liner IF you promise it fixed the issue for you in a manual run.

Or, include a screenshot? <3

**Comment by Kovner** [comment]
The bitmoji of me Nailing it wasn't sufficient?

image

image

**Comment by LGraber** [comment]
:rocket:

**Pull request merged**
