### PR TITLE
Adds hidden_views parameter to publish()

### PR DESCRIPTION
**Pull request by scuml**
Resolves Issue #354 

Adds `hidden_views` as a parameter to publish().

```
new_workbook = server.workbooks.publish(
        workbook_item=new_workbook, file_path=filename, mode="CreateNew",
        hidden_views=["Sheet 44", "Test View"],
) 
```

### CODE REVIEW

**Comment by shinchris** [comment]
Thanks for submitting a pull request!
Before we can merge this change, could you read and sign our [Contributor License Agreement](http://tableau.github.io/contributing.html)?

**Comment by scuml** [comment]
Send it in on Friday afternoon.

**Comment by RussTheAerialist** [comment]
Can confirm receipt of the CLA

**Comment by Sambhawam07** [comment]
Is there a way to get the list of hidden views using the api?
In order to get the data from the hidden views.

**Comment by jmeisele** [comment]
Same question ^

**Comment by bcantoni** [comment]
@jmeisele if you don't mind, could you create a new issue for that question? The we can address it over there instead of getting lost on this closed PR.

**Comment by cody2094** [comment]
@bcantoni Did that new issue get created for that question? I have a similar need

**Comment by bcantoni** [comment]
Hi @cody2094 I don't see one - if you don't mind could you create an issue with some details?

**Comment by cody2094** [comment]
@bcantoni I started to, but after I looked into this a little more, it seems to me as though the views aren't necessarily "hidden", they are just not in Tableau server at all. I'm not sure it warrants an issue/feature request if the data isn't even in Tableau Server. Seems like this would be a big feature request, you mind confirming that something like that is even reasonable for me to post an issue for?

**Comment by SaraUris** [comment]
Is there a way to hide all worksheets instead of giving a list of names?

**Pull request merged**
