### PR TITLE
fix revision references where xml returned does not match docs

### PR DESCRIPTION
**Pull request by jharris126**
Fixes Issue #1175

XML returned by Tableau REST API differs from what TSC code is expecting as well as the [sample response in the docs site](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_revisions.htm#get_workbook_revisions). This change fixes the 4 `RevisionItem` properties with references mismatch between the xml response and the docs.

### CODE REVIEW

**Comment by jharris126** [comment]
Hmm... just signed the CLA, how do I rerun the build?

**Comment by jorwoods** [comment]
@jharris126 the test probably needs to be updated as well. https://github.com/tableau/server-client-python/blob/97747b7b253d659de7871e0b3f20c0a1702b4c2a/test/assets/workbook_revision.xml#L5

**Comment by jacalata** [comment]
@alexepperly fair comment, there is always other stuff going on but a little polite impatience can definitely push things along :)

**Comment by alexepperly** [comment]
> @alexepperly fair comment, there is always other stuff going on but a little polite impatience can definitely push things along :) 

image

**Pull request merged**
